CREATE TABLE CATEGORYCHART (
    PICKUP_ID INTEGER,
    CATEGORY_ID INTEGER,
    CATEGORY_WEIGHT INTEGER NOT NULL,

    FOREIGN KEY (PICKUP_ID) REFERENCES PICKUPS(PICKUP_ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE CASCADE,

    PRIMARY KEY (PICKUP_ID, CATEGORY_ID)
);