CREATE TABLE ITEMCHART (
    PICKUP_ID INTEGER,
    CATEGORY_ID INTEGER,
    ITEM_ID INTEGER,
    ITEM_WEIGHT INTEGER NOT NULL,

    FOREIGN KEY (PICKUP_ID) REFERENCES PICKUPS(PICKUP_ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE CASCADE,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE,

    PRIMARY KEY (PICKUP_ID, CATEGORY_ID, ITEM_ID)
);